FROM nginx:1.25-alpine

ENV LANG=C.UTF-8

RUN mkdir /etc/nginx/ssl

# Simple self signed certificate
#COPY ./scripts/nginx/ssl/server.crt /etc/nginx/ssl/server.crt
#COPY ./scripts/nginx/ssl/server.key /etc/nginx/ssl/server.key

# More elaborate certificate
COPY ./scripts/nginx/ssl/cert.pem /etc/nginx/ssl/server.crt
COPY ./scripts/nginx/ssl/cert-key.pem /etc/nginx/ssl/server.key

RUN chmod 400 /etc/nginx/ssl/server.key

EXPOSE 80
EXPOSE 443