services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx-ssl
    volumes:
      - ./scripts/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
      - 443:443
  